# Generated by Django 3.2.12 on 2022-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('all_alerts', models.IntegerField()),
                ('sum_all_alerts', models.IntegerField()),
                ('shooting_alerts', models.IntegerField()),
                ('sum_shooting_alerts', models.IntegerField()),
            ],
        ),
    ]
