# Generated by Django 3.2.12 on 2022-03-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyAlerts',
            new_name='DailyAlert',
        ),
    ]
