# Generated by Django 3.2.12 on 2022-03-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0002_rename_dailyalerts_dailyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyalert',
            name='robbery_alerts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailyalert',
            name='sum_robbery_alerts',
            field=models.IntegerField(default=1),
        ),
    ]
